### ISSUE TITLE
oye

### ISSUE THREAD

**Issue by BlissSc** [JeffreyRandom/discord-jeffrey-bot#1]
Pusiste tu token en bot.js, usa .env o alguien podría modificar tu bot o hacer cualquier cosa

**Comment by JeffreyRandom** [comment]
¿Algún tutorial? soy nuevo en esto de bots :)

**Comment by BlissSc** [comment]
Esta el de crater, el explica como poner el dato en un .env http://craterdev.com/documentacion-mybot/alojando-bot-en-heroku.html
